# Usa una imagen base de Python.
FROM python:3.11

# Establece el directorio de trabajo dentro del contenedor.
WORKDIR /app

# Instala las dependencias del sistema operativo que tu aplicación necesita.
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libxrender1

# Copia los archivos de tu proyecto al directorio de trabajo.
COPY . .

# Instala las librerías de Python desde requirements.txt.
RUN pip install --no-cache-dir -r requirements.txt

# Define el comando que se ejecutará al iniciar el contenedor.
CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000" ]

